### ISSUE TITLE
License status

### ISSUE THREAD

**Issue by hwo411** [xupit3r/wuzzy#10]
Hello,

We want to use https://github.com/postlight/mercury-parser in our app, and found, that your library is a dependency of this project.

However, package.json file of this library states that the license of you library is GPL, without specifying the version. There are no other license references in your repository.

Could you please confirm that GPL is intended for this library and clarify the version?

Mercury-parser is under MIT, so GPL creates a license conflict with your library (presumably, they just didn't expect GPL here), which means we won't be able to use mercury parser until they replace your library, or unless you decide to set the license to some permissive one. Their project isn't very active, so I'm not sure how and when they resolve this issue if it's indeed the case that your software is licensed under some GPL version.

Thank you in advance.

**Comment by xupit3r** [comment]
hello.

thanks for reaching out. 

so, when i first wrote all this stuff, i was not particularly focused on the licensing choice. the GPL license was something i had heard of and agreed with. that being said, i am totally fine with switching the license over to an MIT license.

**Comment by xupit3r** [comment]
whoops. didn't mean to close this! re-opening.

**Comment by xupit3r** [comment]
okie dokie, license has been officially moved to MIT. let me know if you have any other questions. take care!

**Comment by hwo411** [comment]
Thank you very much @xupit3r!
