### ISSUE TITLE
Outdated lodash version

### ISSUE THREAD

**Issue by efeichen** [xupit3r/wuzzy#4]
Hi! I just started using your package and NPM is telling me that your current lodash dependency version has prototype pollution vulnerability.

I'm wondering if you could update the package to the latest version? Thank you! :)

**Comment by xupit3r** [comment]
sorry for the delay in responding here. the identified vulnerabilities should be addressed with pull requests #5 (thanks @malob!) and #6. i have also published a new version 0.1.4 of the package to npm.

thanks for the issue report!
